### ISSUE TITLE
[BUG] password encryption for Langtype 4 & 7, client login password error

### ISSUE THREAD

**Issue by LiMoon** [Neo-Mind/WARP#94] opened 2022-04-09 13:30 UTC
I am not very good at English, and this is a machine translation. 
But I would like to ask...

The nemo version of 4144 "disable password encryption (Restore login packet 0x64)" can fix "langtype 4" still login game, but I try to use "Use Old Login Packet" of "WARP", but the game appears "password error". I wonder if the "Use Old Login Packet" of "WARP" has a problem with the patch?

Thank you, client version is 2021-11-17.

Maybe can see if this issues not modified?
https://gitlab.com/4144/Nemo/-/issues/104#note_740504492

**Comment by Neo-Mind** [comment] 2022-08-23 05:46
You are mixing up 2 different patches.
- **`Disable password encryption for LT 4 & 7`** (_This need to be added in WARP_)
- **`Use old login packet`** (_This is working as intended_)

**Comment by Neo-Mind** [comment] 2022-08-23 08:00
Will push the new patch soon.

**Comment by Neo-Mind** [comment] 2022-09-05 17:54
The new patch has been added. Check it out.

**Comment by Neo-Mind** [comment] 2022-09-13 18:42
@LiMoon Hope you were able to make use of the new patch.
I will be closing this tomorrow

**Closed as completed** 2022-09-24 09:08 UTC
Labels: bug, completed
