### ISSUE TITLE
Add case-insensitive cash shop search patch  

### ISSUE THREAD

**Issue by patcervatos** [Neo-Mind/WARP#13] opened 2021-02-08 04:51 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice to have this patch like the one that you have for the storage search
**Describe the solution you'd like**
As the title implies, search would be case-insensitive.

**Additional context**

**Comment by Neo-Mind** [comment] 2022-03-01 20:54
This will be added soon.

**Comment by Neo-Mind** [comment] 2022-03-04 18:12
Patch has been added. Check it out.

**Comment by Neo-Mind** [comment] 2022-08-06 07:10
Closing this, since there is no feedback. Hope it is working as intended.

**Closed as completed by Neo-Mind** 2022-08-06 07:10 UTC
Labels: enhancement, completed
