### ISSUE TITLE
[BUG] Custom Shield Patch

### ISSUE THREAD

**Issue by SirHaziel** [Neo-Mind/WARP#37] opened 2021-06-10 16:10 UTC
**Describe the bug**
Applying the Custom Shield patch delivers everything it promises as intended, however, it breaks the appearance of Bows and Arrows. For Snipers, it won't show Bows on attack animations (but will on standing poses) nor arrows.
For Stalkers, it won't show the bow (or the arrows) at all.

**To Reproduce**
Steps to reproduce the behaviour:
1. Apply Custom Shield Patch (Tested on 2018-06-21a-RagexeRE)
2. Be a Sniper or Stalker
3. Attack any monster with an Arrow equipped.

**Expected behaviour**
No changes on any WeaponTypes.

**Screenshots**
https://i.imgur.com/IeovwrP.gif

**Additional Details (Complete all relevant items below)**
 - Enable Custom Shields
 - 127 ID Limit
 - 2018-06-21a-RagexeRE
 - Windows 10 64bit

**Comment by Neo-Mind** [comment] 2021-06-10 21:30
Fixed the issue in local area. Will be pushed soon.

**Comment by Neo-Mind** [comment] 2021-06-11 20:42
Check it now @SirHaziel

**Comment by Neo-Mind** [comment] 2021-06-19 18:07
Closing this since it has been confirmed.

**Closed as completed** 2021-06-19 18:07 UTC
Labels: bug, completed
