### ISSUE TITLE
[BUG] Enable Multiple GRF

### ISSUE THREAD

**Issue by admkakaroto** [Neo-Mind/WARP#5] opened 2021-01-16 16:47 UTC
**Describe the bug**
It's a very simple bug, when using the 'Read Multigrf' patch on client version 2020-09-02bRagexeRE, it applies without error, but it doesn't work.

**To Reproduce**
1. Just apply the patch on the informed client version, try to read more than 5 grf's, it won't.

I didn't get to test with less than 3 grfs.

**Additional Details (Complete all relevant items below)**
 - Patch/Extension name: Enable Multiple GRF
 - Build Dates affected: 2020-09-02bRagexeRE
 - OS: Win10 x 64

**Comment by Neo-Mind** [comment] 2021-01-20 12:35
@admkakaroto  Just now tested the patch. It's working fine for me, I used a DATA.INI with 7 grfs.
Please make sure you are using the latest commit and check again.

**Comment by admkakaroto** [comment] 2021-01-20 13:07
> @admkakaroto Just now tested the patch. It's working fine for me, I used a DATA.INI with 7 grfs.
> Please make sure you are using the latest commit and check again.

Ok, i'm at work now, but in 2 hours i will come to home, so, i will test this, thanks.

**Comment by Neo-Mind** [comment] 2021-01-20 13:28
In case you didn't know, the file names in DATA.INI should be numbered according to priority.
Lower numbered ones override the higher numbers.

This is especially important because official grfs would have client info inside so your grfs need to be set with a lower number than them.

**Comment by Neo-Mind** [comment] 2021-01-21 16:32
@admkakaroto any update?

**Comment by admkakaroto** [comment] 2021-01-21 23:12
@Neo-Mind Oops, I apologize for the delay, I had personal problems and so I couldn't answer.

Well, I updated WARP:
![a111](https://user-images.githubusercontent.com/6227618/105423674-bdedfa00-5c24-11eb-89d0-d9ea12b5d19c.png)

I added encryption on the client using the GRF Editor.
But when I tried to log in, the problem persists.
![a222](https://user-images.githubusercontent.com/6227618/105423745-e1b14000-5c24-11eb-9ae3-a2f5bfdf6b59.png)

To make sure that the problem is with reading the grfs, I will merge in ALL the grfs, use only one single grf, I will give a feedback here in a few minutes.

**Comment by admkakaroto** [comment] 2021-01-21 23:47
Well, I put all the grf's in one, it didn't work.

So I removed the encryption from the GRF/Client and then it was possible to login.

![a222](https://user-images.githubusercontent.com/6227618/105426414-da406580-5c29-11eb-8619-29d8fcc84ec6.png)

**Comment by Neo-Mind** [comment] 2021-01-22 03:59
That sounds like an issue with the way the encrypted files are being read rather than the patch itself.

Did you generate the DLL file and use that? or only did the Encryption part?

For decrypting, the client needs the DLL and the client itself would need modification in case the DLL's name is different.

**Comment by admkakaroto** [comment] 2021-01-22 10:47
Yes, I used the file to decrypt, I haven't tested it with several unencrypted grfs, but I will test it here, yesterday I tested it with only 2 unencrypted grfs.

**Comment by admkakaroto** [comment] 2021-01-22 22:03
I tested with several grfs, all without encryption, well, I managed to login to the character selection screen, I couldn't get into the game, but I believe there is a problem with encryption. Using the old Nemo updated by 4144, I can log into the game normally, but without encryption.

**Comment by Neo-Mind** [comment] 2021-01-25 04:32
Yea you should inform Tokei about the issue with Encryption. 
Looks like the client might be expecting a newer version of CPS.

**Comment by admkakaroto** [comment] 2021-01-25 23:15
I will try to call Tokei to this issue.

**Comment by admkakaroto** [comment] 2021-01-25 23:18
![tenor](https://user-images.githubusercontent.com/6227618/105778139-7b8d2b80-5f4a-11eb-9ebb-14eb3bd23e1f.gif)

@Tokeiburu

**Comment by SirHaziel** [comment] 2021-01-30 23:13
@admkakaroto would you be so kind to contact me on Discord?

**Comment by admkakaroto** [comment] 2021-01-31 16:51
Sure!

**Comment by Neo-Mind** [comment] 2021-02-23 18:12
Since the issue isn't specific to WARP. Shall I close this?

**Comment by admkakaroto** [comment] 2021-02-24 10:38
> Since the issue isn't specific to WARP. Shall I close this?

Yes

**Closed as completed** 2021-02-24 15:54 UTC
Labels: bug
